<?php

return [
    'permissions' => [
        ['slug' => 'view-dashboard', 'name' => 'View Dashboard', 'group' => 'operations', 'description' => 'Access the main admin dashboard.'],
        ['slug' => 'view-orders', 'name' => 'View Orders', 'group' => 'operations', 'description' => 'View and create bakery orders.'],
        ['slug' => 'manage-order-approvals', 'name' => 'Manage Order Approvals', 'group' => 'operations', 'description' => 'Accept or reject submitted orders.'],
        ['slug' => 'view-bookings', 'name' => 'View Advance Bookings', 'group' => 'operations', 'description' => 'Review upcoming advance bookings.'],
        ['slug' => 'manage-branches', 'name' => 'View Branches', 'group' => 'production', 'description' => 'Review production branches and capacity.'],
        ['slug' => 'manage-branch-master-data', 'name' => 'Manage Branch Master Data', 'group' => 'production', 'description' => 'Create, update, and delete branches.'],
        ['slug' => 'manage-all-branches', 'name' => 'Manage All Branches', 'group' => 'production', 'description' => 'View and manage records across every branch instead of only an assigned branch.'],
        ['slug' => 'delete-branches-with-orders', 'name' => 'Delete Branches With Orders', 'group' => 'production', 'description' => 'Delete branches even when they already have related order history.'],
        ['slug' => 'manage-products', 'name' => 'Manage Products', 'group' => 'production', 'description' => 'Create, update, and delete products.'],
        ['slug' => 'delete-products', 'name' => 'Delete Products', 'group' => 'production', 'description' => 'Delete products from the product catalog management screen.'],
        ['slug' => 'manage-inventory', 'name' => 'Manage Inventory', 'group' => 'production', 'description' => 'Record branch opening stock, production, sales, and closing stock.'],
        ['slug' => 'manage-all-inventory', 'name' => 'Manage All Inventory', 'group' => 'production', 'description' => 'Access and update inventory sheets across every branch instead of only an assigned branch.'],
        ['slug' => 'manage-categories', 'name' => 'Manage Product Categories', 'group' => 'production', 'description' => 'Create, update, and delete product categories.'],
        ['slug' => 'view-reports', 'name' => 'View Reports', 'group' => 'analytics', 'description' => 'Access reports and operational insights.'],
        ['slug' => 'manage-users', 'name' => 'Manage Users', 'group' => 'administration', 'description' => 'Create, update, suspend, and delete users.'],
        ['slug' => 'manage-roles', 'name' => 'Manage Roles', 'group' => 'administration', 'description' => 'Create and manage role definitions.'],
        ['slug' => 'manage-permissions', 'name' => 'Manage Permissions', 'group' => 'administration', 'description' => 'Create and manage permission definitions.'],
        ['slug' => 'manage-integration-settings', 'name' => 'Manage System Settings', 'group' => 'administration', 'description' => 'Update order limits, notifications, and integration settings.'],
    ],

    'roles' => [
        [
            'slug' => 'super_admin',
            'name' => 'Super Admin',
            'description' => 'Full platform control across operations, products, users, and settings.',
            'permissions' => [
                'view-dashboard',
                'view-orders',
                'manage-order-approvals',
                'view-bookings',
                'manage-branches',
                'manage-branch-master-data',
                'manage-all-branches',
                'delete-branches-with-orders',
                'manage-products',
                'delete-products',
                'manage-inventory',
                'manage-all-inventory',
                'manage-categories',
                'view-reports',
                'manage-users',
                'manage-roles',
                'manage-permissions',
                'manage-integration-settings',
            ],
        ],
        [
            'slug' => 'production_branch_manager',
            'name' => 'Production Branch Manager',
            'description' => 'Supervises branch operations, approvals, production capacity, and reporting.',
            'permissions' => [
                'view-dashboard',
                'view-orders',
                'manage-order-approvals',
                'view-bookings',
                'manage-branches',
                'manage-products',
                'manage-inventory',
                'view-reports',
            ],
        ],
        [
            'slug' => 'internal_outlet',
            'name' => 'Internal Outlet',
            'description' => 'Places and tracks orders for internal outlet demand.',
            'permissions' => [
                'view-dashboard',
                'view-orders',
            ],
        ],
        [
            'slug' => 'whole_marketer',
            'name' => 'Whole Marketer',
            'description' => 'Places and tracks wholesale orders and advance bookings.',
            'permissions' => [
                'view-dashboard',
                'view-orders',
                'view-bookings',
            ],
        ],
        [
            'slug' => 'public_retailer',
            'name' => 'Public Retailer',
            'description' => 'Basic retail ordering profile.',
            'permissions' => [],
        ],
    ],
];
